spring.application.name=gestorEmprestimosOnBoarding

# Configuração De banco de Dados para conectar
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_emprestimos
spring.datasource.username=postgres
spring.datasource.password=password123

# Mostra no console os comandos SQL que o Java está executando (ótimo para debugar!)
spring.jpa.show-sql=true

# IMPORTANTE: Como você já tem um script SQL pronto, mantenha como 'none' ou 'validate'.
# Se deixar como 'update' ou 'create', o Spring pode tentar reescrever as tabelas por cima do seu script!
spring.jpa.hibernate.ddl-auto=none

# Exibe logs detalhados sobre as requisições web e rotas mapeadas
logging.level.web=DEBUG
logging.level.org.springframework.web=DEBUG